# -*- mode: ruby -*-
# vi: set ft=ruby :

BATCH_VAGRANT_VERSION = "2"

Vagrant.configure(BATCH_VAGRANT_VERSION) do |config|

  config.vm.box = "batch"

  config.vm.define "batch" do |batch|
    batch.vm.provider "virtualbox" do |v, override|
      override.vm.box = "ubuntu/trusty64"
      v.memory = 2048
      v.cpus = 4
    end

    batch.vm.network "private_network", ip: "192.168.50.7"

    # BATCH API
    batch.vm.network "forwarded_port", guest: 8087, host: 58087, auto_correct: true

    # ZOOKEEPER
    batch.vm.network "forwarded_port", guest: 2181, host: 2181, auto_correct: true

    # KAFKA
    batch.vm.network "forwarded_port", guest: 9092, host: 9092, auto_correct: true

    # REDIS
    batch.vm.network "forwarded_port", guest: 6379, host: 6379, auto_correct: true

    batch.vm.synced_folder "../batch", "/srv/unified/batch/"
    batch.vm.synced_folder "/tmp", "/tmp/scratch"

    if ENV['docker'] == 1 
      batch.vm.provision "docker", run: "always" do |d|
        d.build_image "/srv/unified/batch/", args: "-t batch"
        d.run "batch", args: "-e HOST=0.0.0.0 -e PORT=8087 -i -t -d --privileged --expose 8087 -p 8087:8087 --name batch"
      end
    else
      batch.vm.provision "shell", run: "always", path: "./conf/vagrant/bootstrap.sh"
      batch.vm.provision "shell", run: "always", inline: "rm /etc/supervisor/conf.d/batch.conf; ln -s /srv/unified/batch/conf/vagrant/supervisor.conf-standalone /etc/supervisor/conf.d/batch.conf; sudo service supervisor stop; sudo service supervisor start; exit 0"
    end

  end
end
